# intro module

import time

def rules():
    print('AHOYIE MATIES!!!!!!! WELCOME TO PIRATE WARS!!!!!!!!!')
    print("Hoiste the flag and prepare to play!")
    time.sleep(2)
    print('MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM')
    print('MMMMMMMMMMMM        MMMMMMMMMMMM')
    print('MMMMMMMMMM            MMMMMMMMMM')
    print('MMMMMMMMM              MMMMMMMMM')
    print('MMMMMMMM                MMMMMMMM')
    print('MMMMMMM                 MMMMMMMM')
    print('MMMMMMM                  MMMMMMM')
    print('MMMMMMM                  MMMMMMM')
    print('MMMMMMM    MMM    MMM    MMMMMMM')
    print('MMMMMMM   MMMMM   MMMM   MMMMMMM')
    print('MMMMMMM   MMMMM   MMMM   MMMMMMM')
    print('MMMMMMMM   MMMM M MMMM  MMMMMMMM')
    print('MMVKMMMM        M        MMMMMMM')
    print('MMMMMMMM       MMM      MMMMMMMM')
    print('MMMMMMMMMMMM   MMM  MMMMMMMMMMMM')
    print('MMMMMMMMMM MM       M  MMMMMMMMM')
    print('MMMMMMMMMM  M M M M M MMMMMMMMMM')
    print('MMMM  MMMMM MMMMMMMMM MMMMM   MM')
    print('MMM    MMMM M MMMMM M MMMM    MM')
    print('MMM    MMMM   M M M  MMMMM   MMM')
    print('MMMM    MMMM         MMM      MM')
    print('MMM       MMMM     MMMM       MM')
    print('MMM         MMMMMMMM      M  MMM')
    print('MMMM  MMM      MMM      MMMMMMMM')
    print('MMMMMMMMMMM  MM       MMMMMMM  M')
    print('MMM  MMMMMMM       MMMMMMMMM   M')
    print('MM    MMM        MM            M')
    print('MM            MMMM            MM')
    print('MMM        MMMMMMMMMMMMM       M')
    print('MM      MMMMMMMMMMMMMMMMMMM    M')
    print('MMM   MMMMMMMMMMMMMMMMMMMMMM   M')
    print('MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM')
    time.sleep(2)
    print('\nCurses! Half your crew has mutanied and stole some ships. They are also after your burried gold!')
    time.sleep(2)
    print('We need to set sail to blow them out of the water. Type the letter and number where you would like to place a ship.')
    print('Vessels can be placed diagonally, but all ship parts must be together.')
    time.sleep(5)
    print('After all 5 of our ships have left port, enter the letter and number to launch a shot at your enemies \nthat are after your booty!')
    time.sleep(3)
    print('Good luck me harties! ARRRRRR!\n')
    time.sleep(2)
    print("\n    Player's Armada")
